### PR TITLE
Bugfix/alan

### PR DESCRIPTION
**Pull request by tacketar**
Fix trailing '/' on normal files with lio_du

### CODE REVIEW

**Comment by PerilousApricot** [comment]
I am not a robot.

-- 
It's dark in this basement.

**Comment by tacketar** [comment]
Just trying to figure out how it went awry.  I was supposed to have just 
added the lio_du trailing "/" fix.  I did a "git pull; git checkout 
master; made my changes; git checkout -b bugfix/alan; git add; git 
commit; git push origin bugfix/alan'  I'm confused where all the other 
changes came from.

Alan

**Comment by PerilousApricot** [comment]
Because you mixed things up and committed the release branch onto master. I'll have to rewrite the history to back it out.

FWIW, the web interface shows you what is about to go in before you try to merge it.

**Comment by tacketar** [comment]
Definitely a screw up on my part.  It was such a simple change I didn't 
pay any attention to the web interface.   Any idea how the release 
branch got intermingled with the master?  I have no idea how I could 
have done that.  I seem to be missing something fundamental.

Alan

**Comment by PerilousApricot** [comment]
Your PR started from the release branch, then you merged it to the master branch. I'm going to rewrite the history now, make sure to fix your local copy.

**Pull request merged**
