### PR TITLE
Bugfix/timecache

### PR DESCRIPTION
**Pull request by PerilousApricot**
PR for Alan's feature branch.

### CODE REVIEW

**Comment by PerilousApricot** [comment]
@tacketar mind if I rewrite to fix your indents?

**Comment by PerilousApricot** [comment]
Fixed via f6cb9b57b5a4f744e836075edae9afdbcad72e85

**Comment by PerilousApricot** [comment]
sorry, 96a14688ef7c0a46946c562cb847817f95843c45

**Comment by tacketar** [comment]
I don't understand what you mean by sorry???  -Alan

**Comment by PerilousApricot** [comment]
Wrong SHA1.

**Pull request closed without merging**
